spring:
  application:
    name: search-service
  profiles:
    active: local
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        listener:
          max-inflight-messages-per-queue: 50
          max-messages-per-poll: 50
          poll-timeout: 10s

server:
  port: 8087

logging:
  level:
    root: INFO

app:
  sqs:
    identity-queue-name: identity-debezium-queue
    listener:
      max-concurrent-messages: 50
      max-messages-per-poll: 50
      poll-timeout-seconds: 10
      message-visibility-seconds: 60
  debezium-ingestion:
    default-table-name: spt_identity
    table-index-map:
      spt_identity: identity_index
    default-id-fields:
      - documentId
      - document_id
      - id
      - identity_id
    table-id-fields:
      spt_identity:
        - id
        - identity_id
      spt_identity_entitlement:
        - id
      spt_application:
        - id

opensearch:
  local:
    host: localhost
    port: 9200
    scheme: https
    username: admin
    password: Tiger@Tiger123
