app.sqs.identity-queue-name=identity-debezium-queue

opensearch.local.host=localhost
opensearch.local.port=9200
opensearch.local.scheme=https
opensearch.local.username=admin
opensearch.local.password=Tiger@Tiger123
