spring.application.name=search-service
spring.profiles.active=local

server.port=8087

logging.level.root=INFO

spring.cloud.aws.region.static=us-east-2
spring.cloud.aws.sqs.listener.max-inflight-messages-per-queue=50
spring.cloud.aws.sqs.listener.max-messages-per-poll=50
spring.cloud.aws.sqs.listener.poll-timeout=10s

app.sqs.listener.max-concurrent-messages=50
app.sqs.listener.max-messages-per-poll=50
app.sqs.listener.poll-timeout-seconds=10
app.sqs.listener.message-visibility-seconds=60

app.debezium-ingestion.data-record-type-index-map.IDENTITY=identity_index
app.debezium-ingestion.data-record-type-id-fields.IDENTITY[0]=iiqId
