app.sqs.identity-queue-name=ONEIAM-OpenSearch-Events-To-SharedService-Queue
app.sqs.queue-url=https://sqs.us-east-2.amazonaws.com/334672676108/ONEIAM-OpenSearch-Events-To-SharedService-Queue
app.sqs.dlq-name=ONEIAM-OpenSearch-Events-To-SharedService-Queue-DLQ
app.sqs.dlq-url=https://sqs.us-east-2.amazonaws.com/334672676108/ONEIAM-OpenSearch-Events-To-SharedService-Queue-DLQ
app.sqs.topic-arn=arn:aws:sns:us-east-2:334672676108:ELV-IAM-OpenSearch-Events
app.sqs.producer-role-arn=arn:aws:iam::334672676108:role/oneiam-ims-eks-service-account-role
app.sqs.consumer-role-arn=arn:aws:iam::334672676108:role/oneiam-ssvc-eks-service-account-role

opensearch.aws.region=us-east-2
opensearch.aws.host=
